Repository Foxterosa/Manaos, pull requests merged in 2020-09, with the labels that each got.

#9 again, traduciendo.
  code/game/movietitles.dm
  code/game/objects/alien_props.dm
  code/game/objects/effects/decals/crayon.dm
  code/game/objects/effects/decals/remains.dm
  code/game/objects/effects/manifest.dm
  code/game/objects/effects/misc.dm
  code/game/objects/effects/portals.dm
  code/game/objects/effects/spiders.dm
  code/modules/culture_descriptor/culture/_culture.dm
  code/modules/culture_descriptor/culture/cultures_skrell.dm
  code/modules/culture_descriptor/faction/faction.dm
  code/modules/culture_descriptor/faction/factions_hidden.dm
  code/modules/culture_descriptor/faction/factions_ipc.dm
  code/modules/culture_descriptor/faction/factions_unathi.dm
  code/modules/culture_descriptor/location/locations_ascent.dm
  code/modules/culture_descriptor/location/locations_skrell.dm
  code/modules/culture_descriptor/location/locations_vox.dm
  code/modules/culture_descriptor/religion/religions_ascent.dm
  code/modules/culture_descriptor/religion/religions_human.dm
  code/modules/culture_descriptor/religion/religions_unathi.dm
  code/modules/culture_descriptor/religion/religions_vox.dm
Labels: Traduccion

#12 Wintercoats para el Loadout (+ un Objeto Custom)
  code/modules/client/preference_setup/loadout/lists/suits.dm
  code/modules/clothing/masks/boxing.dm
  icons/mob/onmob/onmob_mask.dmi
  icons/obj/clothing/obj_mask.dmi
  maps/torch/loadout/loadout_head.dm
  maps/torch/loadout/loadout_suit.dm
Labels: 💡Feature

#8 Feedback mapa de eventos
  code/datums/vote/transfer.dm
  code/game/area/Space Station 13 areas.dm
  code/game/objects/items/weapons/flamethrower.dm
  code/modules/admin/verbs/getlogs.dm
  icons/obj/surgery.dmi
  maps/away/derelict/derelict-station.dmm
  maps/torch/job/command_jobs.dm
  maps/torch/job/hestia_jobs.dm
  maps/torch/torch4_deck2.dmm
  maps/torch/z4_eventos.dmm
  maps/~mapsystem/maps_unit_testing.dm
Labels: Fix, 🗺️Mapeo

#39 Mejoras a Ciencias Parte 1 (R&D)
  code/game/machinery/_machines_base/stock_parts/legacy_parts.dm
  code/modules/hydroponics/seed_storage.dm
  code/modules/power/fusion/fusion_circuits.dm
  code/modules/research/circuitprinter.dm
  code/modules/research/designs/_designs.dm
  code/modules/research/designs/design_aimodule.dm
  code/modules/research/designs/designs_biostorage.dm
  code/modules/research/designs/designs_bluespace.dm
  code/modules/research/designs/designs_circuits.dm
  code/modules/research/designs/designs_disk.dm
  code/modules/research/designs/designs_exosuits.dm
  code/modules/research/designs/designs_hud_optical.dm
  code/modules/research/designs/designs_implant.dm
  code/modules/research/designs/designs_medical.dm
  code/modules/research/designs/designs_mining.dm
  code/modules/research/designs/designs_modular_computer.dm
  code/modules/research/designs/designs_powercell.dm
  code/modules/research/designs/designs_rig_modules.dm
  code/modules/research/designs/designs_singletons.dm
  code/modules/research/designs/designs_smes_coil.dm
  code/modules/research/designs/designs_stock_part.dm
  code/modules/research/designs/designs_synthstorage.dm
  code/modules/research/designs/designs_tool.dm
  code/modules/research/protolathe.dm
  code/modules/research/rdconsole.dm
  icons/obj/stock_parts.dmi
Labels: 💡Feature

#40 Guitarra electrica
  code/modules/synthesized_instruments/instrument_data/guitar.dm
  code/modules/synthesized_instruments/real_instruments/Guitar/guitar.dm
  code/modules/synthesized_instruments/samples/guitar/crisis_elec/C2.ogg
  code/modules/synthesized_instruments/samples/guitar/crisis_elec/C3.ogg
  code/modules/synthesized_instruments/samples/guitar/crisis_elec/C4.ogg
Labels: 💡Feature

#41 Retoques en armas de infanteria, magistrado y speedloaders
  code/modules/projectiles/guns/energy/secure.dm
  code/modules/projectiles/guns/projectile/pistol.dm
  icons/mob/onmob/items/lefthand_guns_secure.dmi
  icons/mob/onmob/items/righthand_guns_secure.dmi
  icons/obj/ammo.dmi
  icons/obj/guns/lawyer.dmi
  maps/torch/infantry/storage.dm
  maps/torch/torch1_deck5.dmm
Labels: 💡Feature

#42 Subfusil FNV-600 laser
  code/modules/projectiles/guns/energy/secure.dm
  code/modules/projectiles/guns/projectile/automatic.dm
  icons/mob/onmob/items/lefthand_guns.dmi
  icons/mob/onmob/items/righthand_guns.dmi
  icons/obj/guns/sec_smg.dmi
  maps/torch/torch5_deck1.dmm
Labels: 💡Feature
